### ISSUE TITLE
Twilio-python not compile friendly

### ISSUE THREAD

**Issue by YourHuckleberry** [twilio/twilio-python#167]
When packaging twilio into an executable (using pyinstaller, in this case) code will crash with:

```
SSLError: [Errno 185090050] _ssl.c:343: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
```

Workarounds are convoluted and complicated when the purpose of the library is to help, not hinder.

[Example of issue](http://stackoverflow.com/questions/21201238/twilio-python-module-errors-after-compiling)

**Comment by mcoles** [comment]
Hey guys. Pardon my late-breaking question. I'm still somewhat of a Python newbie, but I faced the same struggle to get my Twilio app to compile to an exe as well, with both py2exe and Pyinstaller. The issue seems to be that http\__init__.py's get_cert_file method is looking for the cacert.pem file in a specific location, without any way to pass a custom path in. Once compiled, the path constructed is within the binary executable, so is no longer valid. Couldn't this be resolved by allowing us to path a specific path in for the cacert.pem file upon instantiation of a new Client? As it is, it seems our solutions is some form of monkey-patching.

thanks!
