### ISSUE TITLE
Twilio Call API

### ISSUE THREAD

**Issue by prakhar21** [twilio/twilio-python#281]
Hi, I was exploring the project, but I am not very clear with how do we speak out custom message while calling someone. I saw `twiML`, which generates XML, how do I map that XML in the `url` property of `client.calls.create()`.

Thanks

**Comment by philnash** [comment]
Hi @prakhar21,

Best plan for you is to probably check out our [quickstart guide for making calls with Python](https://www.twilio.com/docs/quickstart/python/rest). Follow that up with the [quickstart guide for receiving calls](https://www.twilio.com/docs/quickstart/python/twiml) and you will learn how TwiML works and get you using it for the first time.

For an even quicker explanation:

When you create a call with Twilio you need to pass a URL to Twilio. When the call connects, [Twilio will make an HTTP request to that URL](https://www.twilio.com/docs/api/twiml/twilio_request) to see what to do next. You need to build an application that can respond to that HTTP request with some TwiML. In order to read something out to the person you called, you can use the [TwiML `<Say>` verb](https://www.twilio.com/docs/api/twiml/say) like this:

```xml
<Response>
  <Say>Hello from my application</Say>
</Response>
```

Once you've checked out the quickstart guide, take a look at our [tutorials](https://www.twilio.com/docs/tutorials) that show how to build more complex applications too.
