### ISSUE TITLE
Module 'twilio.jwt' has no attribute 'encode'

### ISSUE THREAD

**Issue by ZuSe** [twilio/twilio-python#337]
**Version:**
**API Subdomain (api/taskrouter/ip_messaging):**

### Code Snippet
```python
capability = TwilioCapability(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
        capability.allow_client_incoming(request.user.id)
        capability.allow_client_outgoing(settings.TWILIO_PHONE_APPLICATION_ID)
        token = capability.generate(expires=60 * 60 * 24)
        return Response({"token": token}, status.HTTP_200_OK)
```

### Exception / Log
```
  File "/home/ppalacin/Development/Repositories/myproject/venv/lib/python3.5/site-packages/twilio/util.py", line 109, in generate
    return jwt.encode(payload, self.auth_token)
AttributeError: module 'twilio.jwt' has no attribute 'encode'
```

### Steps to Reproduce
1. Install twilio client 6.1
2. Try to generate a new Capability Token with valid credentials 
3. Error is thrown

**Comment by ZuSe** [comment]
if I change the import statement in utils.py:

`from . import jwt`
to
`import jwt`

everything works

**Comment by efossier** [comment]
@ZuSe That file seems to be left over from previous versions, we no longer have a twilio/util.py so it looks like it was mistakenly included in the distribution. Therefore there may be multiple out dated pieces of code in there.

If you are looking for the equivalent of TwilioCapability in the new library take a look at `ClientCapabilityToken` in `twilio.jwt.client`. The interface is the same except to produce the token you call `to_jwt` instead of `generate`. This was part of an effort to unify all our jwt based tokens into one common base class.

Also the reason that changing `from . import jwt` to `import jwt` works is because in 5.x we had our own implementations `encode` in a module named `jwt` wherease in 6.x we now use use the 3rd party jwt library for encoding/decoding.

**Comment by efossier** [comment]
Heres an equivalent code snippet in 6.x:
```python
capability = ClientCapabilityToken(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
        capability.allow_client_incoming(request.user.id)
        capability.allow_client_outgoing(settings.TWILIO_PHONE_APPLICATION_ID)
        token = capability.to_jwt(ttl=60 * 60 * 24)
        return Response({"token": token}, status.HTTP_200_OK)
```
