### ISSUE TITLE
Verbs not properly nested in XML

### ISSUE THREAD

**Issue by kylefrost** [twilio/twilio-python#341]
**Version:**
6.3.0
**API Subdomain (api/taskrouter/ip_messaging):**
twilio.twiml.VoiceResponse

### Code Snippet
```python
@app.route('/ivr/welcome', methods=['POST'])
def welcome():
    response = VoiceResponse()
    with response.gather(numDigits=1, action=url_for('menu'), method='POST') as g:
        g.say('Welcome to my IVR system.')
    return twiml(response)
```

### *Expected* TwiML Response
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Gather action="/ivr/menu" method="POST" numdigits="1">
        <Say>Welcome to my IVR system.</Say>
    </Gather>
</Response>
```

### *Actual* TwiML Response
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Gather action="/ivr/menu" method="POST" numdigits="1" />
    <Say>Welcome to my IVR system.</Say>
</Response>
```

### Steps to Reproduce
1. Use code provided with appropriate imports
2. Print `str(response)` to view generated TwiML

### More Information
Basically, it appears that when trying to use the `say` method of `gather`, instead of nesting the `Say` verb inside of the `Gather`, it appends it to the end after the `Gather`.

**Comment by kylefrost** [comment]
Fix for this issue in #343

**Comment by yfurbach** [comment]
@kylefrost We have run into the same issue while upgrading from 5.6.0 to 6.3.0, however, there seems to have been a change of behaviour for all verbs in version 6 and therefore I would consider your fix inappropriate, as it half- re-implements the old behaviour for one verb, but only in combination with the with-statement.

The change of behaviour for all verbs was in 
```python
class TwiML(object):
...
    def append(self, verb):
       ...
        self.verbs.append(verb)
        return self
```
This change of behaviour was committed [here](https://github.com/twilio/twilio-python/commit/c374d0bbaa0e29d740dee965a1061c444935e31b)
In version 5 the `append` method returned the verb instead of `self`

However, what confuses me is that the docstring still states that the `Gather` will be returned. So maybe this should be updated, or the change of behaviour reconsidered.
```python
    def gather(self,
               action=None,
               method=None,
               timeout=None,
               finish_on_key=None,
               num_digits=None,
               **kwargs):
        """
        Add a new <Gather> element

        :param action: action URL
        :param method: action URL method
        :param timeout: time to wait while gathering input
        :param finish_on_key: finish on key press
        :param num_digits: digits to collect
        :param kwargs: additional attributes
        :return: <Gather> element
        """
        return self.append(Gather(
            action=action,
            method=method,
            timeout=timeout,
            finish_on_key=finish_on_key,
            num_digits=num_digits,
            **kwargs
        ))
```

**Comment by ilanbiala** [comment]
@kylefrost you should be able to do:
```
g = Gather(...)
g.say(...)

r = VoiceResponse(...)
r.append(g)
```

Does this not work for you?
