### ISSUE TITLE
Migration Guide for 6+ missing a lot

### ISSUE THREAD

**Issue by anotherstarburst** [twilio/twilio-python#344]
### Steps to Reproduce
1. Use version ('5', '7', '0')
2. Try upgrade to ('6', '3', '0') - using the migration guide
3. Watch as everything fails 

# Changes I've found so far that are **not** included in the [migration guide](https://www.twilio.com/docs/libraries/python/migration-guide)

### twiml.Response()

Now has VoiceResponse and MessageResponse not just twiml.Response()

### dial verb

`resp.dial(callerId = number_for_caller_id).conference(...` throws 

> "dial() takes at least 2 arguments"

The first argument should have been passed from resp I guess. Logging my `resp` xml gives me 

```
<?xml version="1.0" encoding="UTF-8"?>
  <Response>
    <Say>Please wait while we connect you to the conference.</Say>
  </Response>
```

which looks fine to me...

https://github.com/twilio/twilio-python/blob/master/twilio/twiml/voice_response.py
shows that number is now a required field - however [the docs](https://www.twilio.com/docs/api/twiml/conference#examples-6) still show that dial can be left without any values, if dialling a conference.

Sidenote:
I also tried using 

```
with resp.dial() as g:
  g.conference(...
```

but saw that there was an outstanding issue in using `with`

## ClientCapabilityToken 

no longer uses .generate()

## TwilioRestException 

import location changed

**Comment by actioncrypto** [comment]
i will also add that at the very least, with a `Gather` verb, the previously typed `numDigits` parameter will now get converted via the `lower_camel` method into `numdigits` which throws a schema validation warning... To side-step this, all source code that worked in v5 needs to change `numDigits` to `num_digits` so that the lower_camel method will properly convert the parameter string into the format TwiML expects.  

From looking at the new source code of the new v6 helper library, it would appear to do this `lower_camel` formatting for all verb params now...

**Comment by ilanbiala** [comment]
@anotherstarburst please reach out to help@twilio.com and hopefully we can resolve this and update the docs as well.
