### ISSUE TITLE
Issues in versions ordering (CHANGELOG.md)

### ISSUE THREAD

**Issue by amureki** [twilio/twilio-python#387]
**Version:** 6.5.2

### Exception/Log
![image](https://user-images.githubusercontent.com/627183/29511646-03c46d46-8660-11e7-84d7-689b18e2d3e4.png)

### Steps to Reproduce
1. Open CHANGELOG.md (https://github.com/twilio/twilio-python/blob/master/CHANGES.md)
2. See, wrong ordering, versions mess (6.6.0 goes before 6.5.2, 6.6.0 is not released)

### Feature Request
I'm proposing to use http://keepachangelog.com/en/1.0.0/ style of writing changelogs, on top of latest released version write `Unreleased` changes, so there would be no misunderstadings.

**Comment by efossier** [comment]
@amureki Good catch and thanks for writing in! Looks like an error on our part when releasing the latest version on Friday, `6.5.2` is the latest version and includes the changes listed under `6.6.0` as well, and we just accidentally put an extra version in the changelog when merging a PR. I went ahead and fixed up the changelog so that it is accurate.

Regarding your proposal for a changelog format, we've talked about this before internally and think this would be a good idea. The changelog is currently generated for the most part however so we will need to make changes to our release pipeline to do this. 

Thanks for the feedback!
