### ISSUE TITLE
Incoming SMS webhook failing validation (non standard SSL port)

### ISSUE THREAD

**Issue by scotta** [twilio/twilio-python#402]
Hi,

I have an incoming SMS webhook using HTTPS but on a non standard port (4433). The incoming POST fails validation unless the changes made in #392 are reverted (i.e. the port number left in for validation). The [security notes](https://www.twilio.com/docs/api/security#notes) don't mention non standard ports. Should only the standard port be removed if using HTTPS?

https://github.com/twilio/twilio-python/blob/119fe50863b2e9df89a56711e8d3410288709593/twilio/request_validator.py#L77

**Comment by scotta** [comment]
Pull request #403

**Comment by valery-trigubov** [comment]
hi there

i've encountered the same problem
- non-default https port (8301) fails validation
- do not omit port fixes the problem
- big thanks @scotta

**Comment by benileo** [comment]
FYI, I got around this issue by doing this, since skipping the validate method would not strip the port. 
We were running on a non-standard port and it failed until we made this change. How come Twilio has not fixed this..?
```
from twilio.request_validator import RequestValidator, compare
validator = RequestValidator(authToken)
computed = validator.compute_signature(url, params)
isValid = compare(computed, signature)
```

**Comment by childish-sambino** [comment]
Did some testing and found that signature generation is not consistent between Voice and SMS webhooks. Voice strips standard and non-standard ports from the URL, which is what #392 was meant to resolve. SMS does not strip the port.

I'm closing #403 since it's been a while so it's pretty out-of-sync and is not a complete fix.

The most _proper_ fix I can think of is to do the validation with and without the port and `or` the results (or short-circuit or whatever). If no port is in the URL, add the standard port (443) since the web server _might_ remove it.

I'll request this gets updated in the docs and add this to our backlog, but open to a PR.

**Comment by williamflynt** [comment]
I'm debugging this issue on my system now, but reading the Twilio docs [here](https://www.twilio.com/docs/usage/security#validating-requests) makes me feel like the `twilio` package for Python is correct in how it's constructing the signature. It feels like Twilio is wrong?

I'm open to doing the PR - if I can figure out what needs fixed.

**Comment by williamflynt** [comment]
Update to previous: I ripped this idea off SO for a C++ version of `twilio`.

This fixes my validation issue.
```python
def rebuild_uri(uri: str) -> str:
    """rebuild a URI with "http://" to "https://" due to bugs in twilio's validator"""
    if "https://" not in uri:
        new_uri = uri.replace("http://", "https://")
        return new_uri
    return uri
```
