### ISSUE TITLE
KeyError: 'caller_name' when calling lookup for phone number with type "carrier"

### ISSUE THREAD

**Issue by DrJackilD** [twilio/twilio-python#472]
*Note: These issues are for bugs and feature requests for the helper libraries.
If you need help or support, please email help@twilio.com and one of our experts
will assist you!*

**Version:** 6.29.0

### Code Snippet
```python
self.client.lookups.phone_numbers(phone_number).fetch(type="carrier").carrier
```

### Exception/Log
```
File "/local/lib/python2.7/site-packages/twilio/rest/lookups/v1/phone_number.py", line 150, in fetch
    return PhoneNumberInstance(self._version, payload, phone_number=self._solution['phone_number'], )
File "/local/lib/python2.7/site-packages/twilio/rest/lookups/v1/phone_number.py", line 182, in __init__
    'caller_name': payload['caller_name'],
KeyError: 'caller_name'
```

### Steps to Reproduce
1. Basically, just call lookup with carrier_info, don't know what number it is.

I can make a PR to make initialize of `_properties` in `PhoneNumberInstance` safe with `dict.get` instead of getattr, what do you think?

**Comment by daryaskopyuk** [comment]
Same problem

**Comment by olehusov** [comment]
Hey, any news? Have the same problem

**Comment by dlchistyakov-allset** [comment]
Hi, Maintainers! 

Can you give any updates or estimates to fix this?

**Comment by childish-sambino** [comment]
I've not been able to recreate this issue using a few different numbers. The API response is _always_ supposed to return the `called_name` attribute so not sure why it's not here.

A couple paths forward here are to either [file a support ticket](https://twilio.com/help/contact), post the number(s) here that are causing issues so I can debug, or email them to me.

I'm also open to modifying the lib so to use `.get()` instead since this is what all/some of the other client libs do in their own languages, but I don't yet know the scope of the impact that would cause.
